### PR TITLE
Prune branch ids when pruning away unsatisfiable disjunction branches

### LINKED ISSUE #7452: Schema disjunctions can lead to assertion failures
## Description
While roleplayers without existing relation types and role types in the schema, the server fails on assertion:
`assertion failed: branch_ids.len() == branches.len()`. 
**It does not affect the release version of TypeDB: a correct result is returned without this check**. 

Also, it works correctly if there are relation types and role types in the database.

We need to verify that removing this assertion is a correct solution, and that we don't miss any corner cases.

## Environment

1. TypeDB distribution: Core
2. TypeDB version: 3.2.0
3. Environment: Mac
4. Client and version: 3.2.0
5. Other details:

## Reproducible Steps

1. Set up
Create a new database
`database create a` (console)

Open a new transaction
`transaction schema a` (console)

2. Execute
```
define
entity person owns name;
attribute name value string;
```

3. Test/Query
Run:
```
match 
{ $t sub $other;  $role is $other; } or
{ $t owns $other;  $role is $other; } or
{ $t relates $role; $role is $other;} or
{ $t plays $role;  $role is $other; };
```

4. Unexpected result (in debug, e.g., local builds)
Server crashes with:
```
thread 'tokio-runtime-worker' panicked at executor/read/nested_pattern_executor.rs:34:9:
assertion failed: branch_ids.len() == branches.len()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Expected result (like in a release version)
```
Finished read query validation and compilation...
Streaming rows...
   ------------
    $other | name
    $role  | name
    $t     | person
   ------------
    $other | person
    $role  | person
    $t     | person
   ------------
    $other | name
    $role  | name
    $t     | name
   ------------
Finished. Total answers: 3

```

### PR DESCRIPTION
**Pull request by krishnangovindraj**
## Product change and motivation
This fixes a bug where the branch_ids go out of sync with the branches.

## Motivation
fixes #7452

### CODE REVIEW

File: ir/pattern/disjunction.rs [hunk 1]
```diff
@@ -57,7 +57,11 @@ impl Disjunction {
     }
 
     pub fn optimise_away_unsatisfiable_branches(&mut self, unsatisfiable: Vec<ScopeId>) {
-        self.conjunctions.retain(|v| !unsatisfiable.contains(&v.scope_id()))
+        let unsatisfiable_branch_ids = self.conjunctions.iter().zip(self.branch_ids.iter())
+            .filter_map(|(conj, branch_id)| unsatisfiable.contains(&conj.scope_id()).then_some(*branch_id))
+            .collect::<Vec<_>>();
+        self.branch_ids.retain(|branch_id| !unsatisfiable_branch_ids.contains(branch_id));
+        self.conjunctions.retain(|conj| !unsatisfiable.contains(&conj.scope_id()))
```
Comment (krishnangovindraj) [inline ir/pattern/disjunction.rs:64]: Yes, the type-system would have caught this if I had used `Vec<(BranchId, Conjunction)>` instead of two separate vecs. But that change was big when I tried it in the morning.

Comment (krishnangovindraj) [reply ir/pattern/disjunction.rs:64]: BranchIDs are allocated from a u16 that keeps going up. The way it's implemented now, they will indeed be sequential.
When a DisjunctionExecutor executes a branch with BranchID `x` it will do `output_row.provenance |= 1 << x;`

**Review by dmitrii-ubskii — APPROVED** [review]

File: ir/pattern/disjunction.rs (hunk 1 above)
Comment (krishnangovindraj) [reply ir/pattern/disjunction.rs:64]: Yes. Unsatisfiable branches will remain 0.

Do we return them in the header?
In the HTTP encoding, no. We only return those indices which are 1. So a provenance of `0..1101` will be encoded as `[0,2,3]`
In the GRPC encoding, I intend to send them over as a little endian byte-array, where one would have to do:
`branch_was_satisfied = byte_array[index / 8] & (1 << index % 8)`

Comment (krishnangovindraj) [reply ir/pattern/disjunction.rs:64]: ohh unsatisfiable. Sorry, I read unsatisfied for some reason.
That's a good question. We should but idk if the pruning optimisation is taken into account. I'll check.

**Comment by flyingsilverfin** [comment]
Was the line of questions here resolved @dmitrii-ubskii ?

File: ir/pattern/disjunction.rs (hunk 1 above)
Comment (krishnangovindraj) [reply ir/pattern/disjunction.rs:64]: I've moved the `extract_query_structure` call to be before we apply transformations, so we get the query-structure as is. Unsatisfiable branches should now be encoded in the response.

File: server/service/http/message/query/query_structure.rs [hunk 2]
```diff
@@ -278,6 +265,9 @@ fn query_structure_edge(
         | Constraint::Value(_)
         | Constraint::Is(_)
         | Constraint::Iid(_) => {}
+        Constraint::IndexedRelation(indexed) => {
+            unreachable!("This is unreachable since we extract query-structure before we apply transformations");
+        }
```
Comment (dmitrii-ubskii) [inline server/service/http/message/query/query_structure.rs:270]: I think we should keep the handling as it was. It was already implemented, and I can totally see us pushing the shortcut edges to initial translation at some point.
